server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF