zuul:
    routes:
        files:
            path: /api/**
            url: http://localhost:8090/api

spring:
    resources:
        static-locations: classpath:/META-INF/resources/webjars/file-storage-ui/1.0.0/